### ISSUE TITLE
Перевести доки на русский

### ISSUE THREAD

**Issue by 4erkashin** [jun-mid/.github#1]
### TODO
Перевести на доки русский. Сначала оригинальный файл дублируем и добавляем пометку _EN. После чего оригинальный же файл (тот который остался без пометки) переводим на русский.

Список файлов для перевода с английского:

- [ ] [Правила поведения](https://github.com/jun-mid/.github/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] [Правила участия в проектах](https://github.com/jun-mid/.github/blob/main/.github/CONTRIBUTING.md)
- [ ] [Соглашение об именовании веток](https://github.com/jun-mid/.github/blob/main/.github/BRANCH_CONVENTION.md)
- [ ] [Соглашение о формате сообщений в коммитах](https://github.com/jun-mid/.github/blob/main/.github/COMMIT_CONVENTION.md)
- [ ] [Шаблон для PR](https://github.com/jun-mid/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
- [ ] [Шаблоны для issue](https://github.com/jun-mid/.github/blob/main/.github/ISSUE_TEMPLATE)
